"""Pydantic schemas package."""

from .contract import (
    ContractAlertResponse,
    ContractCreate,
    ContractDocumentResponse,
    ContractListResponse,
    ContractResponse,
    ContractSummary,
    ContractType,
    ContractUpdate,
    CostsPeriod,
)
from .ticket import (
    TicketAttachmentCreate,
    TicketAttachmentResponse,
    TicketAttachmentStatus,
    TicketAttachmentUpdate,
    TicketCategory,
    TicketCommentCreate,
    TicketCommentResponse,
    TicketCommentUpdate,
    TicketCreate,
    TicketDraft,
    TicketListResponse,
    TicketPriority,
    TicketResponse,
    TicketStatus,
    TicketSummary,
    TicketTimelineEntryResponse,
    TicketUpdate,
)

__all__ = [
    # Contract schemas
    "ContractType",
    "CostsPeriod",
    "ContractCreate",
    "ContractUpdate",
    "ContractResponse",
    "ContractListResponse",
    "ContractSummary",
    "ContractDocumentResponse",
    "ContractAlertResponse",
    # Ticket schemas
    "TicketStatus",
    "TicketCategory",
    "TicketPriority",
    "TicketCreate",
    "TicketUpdate",
    "TicketResponse",
    "TicketListResponse",
    "TicketDraft",
    "TicketSummary",
    "TicketAttachmentCreate",
    "TicketAttachmentUpdate",
    "TicketAttachmentResponse",
    "TicketAttachmentStatus",
    "TicketTimelineEntryResponse",
    "TicketCommentCreate",
    "TicketCommentUpdate",
    "TicketCommentResponse",
]
